// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkbzmcbtrjbekshkqbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a2J6bWNidHJqYmVrc2hrcWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTM5NTcsImV4cCI6MjA1NDc4OTk1N30.PPME_1p4P2x4uHugLrFywqDTUd5Xc_ilUJdTHine2k4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);